server.port=8083
spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=luiz
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Comunicacao com outros servicos via nome do container Docker
product.service.url=http://product-service:8082
shipping.service.url=http://shipping-service:8084

# Actuator
management.endpoints.web.exposure.include=health,info