server.port=8081
spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=luiz
spring.datasource.driver-class-name=org.postgresql.Driver

# Nao tenta criar/alterar tabelas automaticamente (usa o SQL que criamos)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Nao falha na inicializacao se o schema SQL nao existir
spring.sql.init.mode=never

# Actuator
management.endpoints.web.exposure.include=health,info