server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**, /users/**

        - id: product-service
          uri: http://product-service:8082
          predicates:
            - Path=/products/**, /upload/**

        - id: order-service
          uri: http://order-service:8083
          predicates:
            - Path=/orders/**

        - id: shipping-service
          uri: http://shipping-service:8084
          predicates:
            - Path=/shipping/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: GET, POST, PUT, DELETE, PATCH, OPTIONS
            allowedHeaders: "*"
            allowCredentials: true